<?php

namespace App\OpenApi;

use OpenApi\Attributes as OA;

/**
 * Root of the OpenAPI document generated by `php artisan l5-swagger:generate`.
 * Endpoint operations live on the controller methods; shared components live in this folder.
 */
#[OA\Info(
    version: '1.0.0',
    description: <<<'TEXT'
        REST API for browsing products, managing a cart, applying promotional codes, checking out and managing orders.

        **Money** is returned as decimal strings (e.g. `"149.99"`) and accepted in dollars; it is stored as integer cents.

        **Errors** share one shape: `{ "message", "code", "details"? }`. Validation errors (`validation_failed`) add an `errors` object keyed by field.

        **Authentication**: call `POST /api/auth/login` (or register), then send `Authorization: Bearer <token>`.
        TEXT,
    title: 'E-Commerce Order & Promotion API',
)]
#[OA\Server(url: '/', description: 'This server')]
#[OA\SecurityScheme(
    securityScheme: 'sanctum',
    type: 'http',
    description: 'Sanctum personal access token from /api/auth/login or /api/auth/register.',
    bearerFormat: 'Sanctum token',
    scheme: 'bearer',
)]
#[OA\Tag(name: 'Auth', description: 'Customer registration and tokens')]
#[OA\Tag(name: 'Products', description: 'Public catalog')]
#[OA\Tag(name: 'Cart', description: 'The authenticated customer\'s cart')]
#[OA\Tag(name: 'Orders', description: 'Checkout, order history and cancellation')]
#[OA\Tag(name: 'Admin: Products', description: 'Requires an administrator token')]
#[OA\Tag(name: 'Admin: Promotions', description: 'Requires an administrator token')]
final class ApiSpecification {}
